#!/bin/bash

## check node installed
if ! type "node" > /dev/null; then
  echo "node is not installed"
  exit 1
fi

## check node version
if ! node --version | grep -E "v(18|20|21|22|24)" > /dev/null; then
  echo "node version should be 18, 20, 21, 22, or 24"
  exit 1
fi

## check npm installed
if ! type "npm" > /dev/null; then
  echo "npm is not installed"
  exit 1
fi

## check .env file
if [ ! -f .env ]; then
  echo ".env file is missing"
  cp .env.example .env
  echo "Copied .env.example to .env. Please edit .env file."
fi

npm ci
