#!/bin/bash

## Check npm is installed
if ! command -v npm > /dev/null; then
  echo "npm is not installed"
  exit 1
fi

## move to frontend directory and start the development server
exec npm run dev
