#!/bin/bash

## Check docker-compose exists
if ! command -v docker-compose > /dev/null; then
  echo "docker-compose is not installed"
  exit 1
fi

## display web urls
echo "Docker Compose Environment:"
echo "Frontend: http://localhost:80"
echo "Backend API: http://localhost:8000"
echo "API Documentation: http://localhost:8000/docs"

## run environment with docker-compose
docker-compose up -d